<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 5.0.1 (Python 3.10.5 on win32)" generated="20220908 14:41:01.626" rpa="false" schemaversion="3">
<suite id="s1" name="Login-Test" source="C:\desty-automacao-test\desty-automacao-test\src\app\test-app\login-test">
<suite id="s1-s1" name="LoginTest" source="C:\desty-automacao-test\desty-automacao-test\src\app\test-app\login-test\LoginTest.robot">
<test id="s1-s1-t1" name="TC4817 - Validar CPF já registrado" line="16">
<kw name="Abrir App" library="Setup">
<kw name="Open Application" library="AppiumFlutterLibrary">
<arg>${APPIUM_SERVER}</arg>
<arg>automationName=${ATOMATION_NAME}</arg>
<arg>platformName=${PLATFORM_NAME}</arg>
<arg>deviceName=${DEVICE_NAME}</arg>
<arg>app=${APP_PATH}</arg>
<doc>Opens a new application to given Appium server.</doc>
<msg timestamp="20220908 14:41:06.285" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0ED8B50&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20220908 14:41:08.703" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0EC3460&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20220908 14:41:11.047" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0EC0400&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20220908 14:41:13.096" level="FAIL">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0ED92A0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</msg>
<status status="FAIL" starttime="20220908 14:41:04.097" endtime="20220908 14:41:13.156"/>
</kw>
<status status="FAIL" starttime="20220908 14:41:04.095" endtime="20220908 14:41:13.157"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${inicial_botao_ja_sou_cliente}</arg>
<status status="NOT RUN" starttime="20220908 14:41:13.157" endtime="20220908 14:41:13.157"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_cpf_texto_cpf}&quot; deve ser &quot;Informe seu CPF para entrar&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:41:13.158" endtime="20220908 14:41:13.158"/>
</kw>
<kw name="Preencher o campo &quot;${input_cpf}&quot; com o valor &quot;${CPF_registrado}&quot;" library="BaseApp" sourcename="Preencher o campo &quot;${elemento}&quot; com o valor &quot;${valor}&quot;">
<status status="NOT RUN" starttime="20220908 14:41:13.158" endtime="20220908 14:41:13.158"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_cpf_botao_avancar_cpf}</arg>
<status status="NOT RUN" starttime="20220908 14:41:13.159" endtime="20220908 14:41:13.159"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_informar_senha}&quot; deve ser &quot;Informe sua senha&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:41:13.159" endtime="20220908 14:41:13.159"/>
</kw>
<kw name="Fechar App" library="Setup">
<status status="NOT RUN" starttime="20220908 14:41:13.159" endtime="20220908 14:41:13.159"/>
</kw>
<status status="FAIL" starttime="20220908 14:41:04.092" endtime="20220908 14:41:13.160">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0ED92A0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</status>
</test>
<test id="s1-s1-t2" name="TC4818 - Validar CPF inválido" line="25">
<kw name="Abrir App" library="Setup">
<kw name="Open Application" library="AppiumFlutterLibrary">
<arg>${APPIUM_SERVER}</arg>
<arg>automationName=${ATOMATION_NAME}</arg>
<arg>platformName=${PLATFORM_NAME}</arg>
<arg>deviceName=${DEVICE_NAME}</arg>
<arg>app=${APP_PATH}</arg>
<doc>Opens a new application to given Appium server.</doc>
<msg timestamp="20220908 14:41:15.214" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0EDAB00&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20220908 14:41:17.251" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0ED9420&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20220908 14:41:19.302" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0EDABF0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20220908 14:41:21.355" level="FAIL">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0EDAD70&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</msg>
<status status="FAIL" starttime="20220908 14:41:13.164" endtime="20220908 14:41:21.359"/>
</kw>
<status status="FAIL" starttime="20220908 14:41:13.164" endtime="20220908 14:41:21.362"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${inicial_botao_ja_sou_cliente}</arg>
<status status="NOT RUN" starttime="20220908 14:41:21.365" endtime="20220908 14:41:21.365"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_cpf_texto_cpf}&quot; deve ser &quot;Informe seu CPF para entrar&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:41:21.367" endtime="20220908 14:41:21.367"/>
</kw>
<kw name="Preencher o campo &quot;${login_cpf_input_cpf}&quot; com o valor &quot;00011112222&quot;" library="BaseApp" sourcename="Preencher o campo &quot;${elemento}&quot; com o valor &quot;${valor}&quot;">
<status status="NOT RUN" starttime="20220908 14:41:21.367" endtime="20220908 14:41:21.367"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_cpf_botao_avancar_cpf}</arg>
<status status="NOT RUN" starttime="20220908 14:41:21.368" endtime="20220908 14:41:21.368"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_cpf_texto_cpf_invalida}&quot; deve ser &quot;CPF inválido&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:41:21.371" endtime="20220908 14:41:21.371"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_cpf_texto_tente_novamente}&quot; deve ser &quot;Tente novamente&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:41:21.373" endtime="20220908 14:41:21.373"/>
</kw>
<kw name="Fechar App" library="Setup">
<status status="NOT RUN" starttime="20220908 14:41:21.374" endtime="20220908 14:41:21.375"/>
</kw>
<status status="FAIL" starttime="20220908 14:41:13.162" endtime="20220908 14:41:21.377">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0EDAD70&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</status>
</test>
<test id="s1-s1-t3" name="TC4819 - Validar CPF não registrado como cliente - 1º login" line="35">
<kw name="Abrir App" library="Setup">
<kw name="Open Application" library="AppiumFlutterLibrary">
<arg>${APPIUM_SERVER}</arg>
<arg>automationName=${ATOMATION_NAME}</arg>
<arg>platformName=${PLATFORM_NAME}</arg>
<arg>deviceName=${DEVICE_NAME}</arg>
<arg>app=${APP_PATH}</arg>
<doc>Opens a new application to given Appium server.</doc>
<msg timestamp="20220908 14:41:23.442" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0FD86D0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20220908 14:41:25.489" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0FD87C0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20220908 14:41:27.538" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0FD8910&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20220908 14:41:29.587" level="FAIL">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0FD8A60&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</msg>
<status status="FAIL" starttime="20220908 14:41:21.386" endtime="20220908 14:41:29.589"/>
</kw>
<status status="FAIL" starttime="20220908 14:41:21.385" endtime="20220908 14:41:29.591"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${inicial_botao_ja_sou_cliente}</arg>
<status status="NOT RUN" starttime="20220908 14:41:29.591" endtime="20220908 14:41:29.591"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_cpf_texto_cpf}&quot; deve ser &quot;Informe seu CPF para entrar&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:41:29.592" endtime="20220908 14:41:29.592"/>
</kw>
<kw name="Preencher o campo &quot;${login_cpf_input_cpf}&quot; com o valor &quot;${cpf_faker}&quot;" library="BaseApp" sourcename="Preencher o campo &quot;${elemento}&quot; com o valor &quot;${valor}&quot;">
<status status="NOT RUN" starttime="20220908 14:41:29.592" endtime="20220908 14:41:29.592"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_cpf_botao_avancar_cpf}</arg>
<status status="NOT RUN" starttime="20220908 14:41:29.593" endtime="20220908 14:41:29.593"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_cpf_texto_cpf_nao_encontrado}&quot; deve ser &quot;CPF não encontrado&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:41:29.593" endtime="20220908 14:41:29.594"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_cpf_texto_cpf_abrir_conta}&quot; deve ser &quot;Abra já a sua conta!&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:41:29.594" endtime="20220908 14:41:29.594"/>
</kw>
<kw name="Fechar App" library="Setup">
<status status="NOT RUN" starttime="20220908 14:41:29.594" endtime="20220908 14:41:29.594"/>
</kw>
<status status="FAIL" starttime="20220908 14:41:21.382" endtime="20220908 14:41:29.595">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0FD8A60&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</status>
</test>
<test id="s1-s1-t4" name="TC4820 - Validar senha incorreta - 1º login" line="45">
<kw name="Abrir App" library="Setup">
<kw name="Open Application" library="AppiumFlutterLibrary">
<arg>${APPIUM_SERVER}</arg>
<arg>automationName=${ATOMATION_NAME}</arg>
<arg>platformName=${PLATFORM_NAME}</arg>
<arg>deviceName=${DEVICE_NAME}</arg>
<arg>app=${APP_PATH}</arg>
<doc>Opens a new application to given Appium server.</doc>
<msg timestamp="20220908 14:41:31.652" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0FDA170&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20220908 14:41:33.701" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0FDA260&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20220908 14:41:35.738" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0FDA3B0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20220908 14:41:37.773" level="FAIL">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0FDA500&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</msg>
<status status="FAIL" starttime="20220908 14:41:29.599" endtime="20220908 14:41:37.776"/>
</kw>
<status status="FAIL" starttime="20220908 14:41:29.599" endtime="20220908 14:41:37.776"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${inicial_botao_ja_sou_cliente}</arg>
<status status="NOT RUN" starttime="20220908 14:41:37.778" endtime="20220908 14:41:37.778"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_cpf_texto_cpf}&quot; deve ser &quot;Informe seu CPF para entrar&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:41:37.779" endtime="20220908 14:41:37.779"/>
</kw>
<kw name="Preencher o campo &quot;${login_cpf_input_cpf}&quot; com o valor &quot;${CPF_registrado}&quot;" library="BaseApp" sourcename="Preencher o campo &quot;${elemento}&quot; com o valor &quot;${valor}&quot;">
<status status="NOT RUN" starttime="20220908 14:41:37.780" endtime="20220908 14:41:37.780"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_cpf_botao_avancar_cpf}</arg>
<status status="NOT RUN" starttime="20220908 14:41:37.780" endtime="20220908 14:41:37.781"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_informar_senha}&quot; deve ser &quot;Informe sua senha&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:41:37.781" endtime="20220908 14:41:37.782"/>
</kw>
<kw name="Preencher o campo &quot;${login_senha_input_senha}&quot; com o valor &quot;${senha_faker}&quot;" library="BaseApp" sourcename="Preencher o campo &quot;${elemento}&quot; com o valor &quot;${valor}&quot;">
<status status="NOT RUN" starttime="20220908 14:41:37.783" endtime="20220908 14:41:37.783"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_senha_botao_avancar}</arg>
<status status="NOT RUN" starttime="20220908 14:41:37.784" endtime="20220908 14:41:37.784"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_senha_erro_login}&quot; deve ser &quot;Não foi possível completar o login&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:41:37.785" endtime="20220908 14:41:37.785"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_mensagem_senha_incorreta}&quot; deve ser &quot;Parece que a senha está incorreta. Tente novamente!&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:41:37.786" endtime="20220908 14:41:37.786"/>
</kw>
<kw name="Fechar App" library="Setup">
<status status="NOT RUN" starttime="20220908 14:41:37.788" endtime="20220908 14:41:37.788"/>
</kw>
<status status="FAIL" starttime="20220908 14:41:29.598" endtime="20220908 14:41:37.790">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0FDA500&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</status>
</test>
<test id="s1-s1-t5" name="TC4827 - Validar senha incorreta - Usuário salvo" line="58">
<kw name="Abrir App" library="Setup">
<kw name="Open Application" library="AppiumFlutterLibrary">
<arg>${APPIUM_SERVER}</arg>
<arg>automationName=${ATOMATION_NAME}</arg>
<arg>platformName=${PLATFORM_NAME}</arg>
<arg>deviceName=${DEVICE_NAME}</arg>
<arg>app=${APP_PATH}</arg>
<doc>Opens a new application to given Appium server.</doc>
<msg timestamp="20220908 14:41:39.855" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0FD9A50&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20220908 14:41:41.908" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0FD9C90&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20220908 14:42:11.042" level="FAIL">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20517ms.
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20517ms.
    at getResponseForW3CError (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)</msg>
<status status="FAIL" starttime="20220908 14:41:37.796" endtime="20220908 14:42:11.053"/>
</kw>
<status status="FAIL" starttime="20220908 14:41:37.795" endtime="20220908 14:42:11.055"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_titulo_login}&quot; deve ser &quot;Login&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:42:11.056" endtime="20220908 14:42:11.056"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_usuario_btn_entrar}</arg>
<status status="NOT RUN" starttime="20220908 14:42:11.057" endtime="20220908 14:42:11.058"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_informar_senha}&quot; deve ser &quot;Informe sua senha&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:42:11.058" endtime="20220908 14:42:11.058"/>
</kw>
<kw name="Preencher o campo &quot;${login_senha_input_senha}&quot; com o valor &quot;${senha_faker}&quot;" library="BaseApp" sourcename="Preencher o campo &quot;${elemento}&quot; com o valor &quot;${valor}&quot;">
<status status="NOT RUN" starttime="20220908 14:42:11.058" endtime="20220908 14:42:11.060"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_senha_erro_login}&quot; deve ser &quot;Parece que a senha está incorreta&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:42:11.060" endtime="20220908 14:42:11.060"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_mensagem_senha_incorreta}&quot; deve ser &quot;Parece que a senha está incorreta. Tente novamente!&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:42:11.062" endtime="20220908 14:42:11.062"/>
</kw>
<kw name="Fechar App" library="Setup">
<status status="NOT RUN" starttime="20220908 14:42:11.064" endtime="20220908 14:42:11.064"/>
</kw>
<status status="FAIL" starttime="20220908 14:41:37.792" endtime="20220908 14:42:11.066">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20517ms.
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20517ms.
    at getResponseForW3CError (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)</status>
</test>
<test id="s1-s1-t6" name="TC4821 - Validar senha bloqueada - 1° Login" line="68">
<kw name="Abrir App" library="Setup">
<kw name="Open Application" library="AppiumFlutterLibrary">
<arg>${APPIUM_SERVER}</arg>
<arg>automationName=${ATOMATION_NAME}</arg>
<arg>platformName=${PLATFORM_NAME}</arg>
<arg>deviceName=${DEVICE_NAME}</arg>
<arg>app=${APP_PATH}</arg>
<doc>Opens a new application to given Appium server.</doc>
<msg timestamp="20220908 14:42:31.622" level="FAIL">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20301ms.
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20301ms.
    at getResponseForW3CError (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)</msg>
<status status="FAIL" starttime="20220908 14:42:11.073" endtime="20220908 14:42:31.624"/>
</kw>
<status status="FAIL" starttime="20220908 14:42:11.072" endtime="20220908 14:42:31.625"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${inicial_botao_ja_sou_cliente}</arg>
<status status="NOT RUN" starttime="20220908 14:42:31.628" endtime="20220908 14:42:31.628"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_cpf_texto_cpf}&quot; deve ser &quot;Informe seu CPF para entrar&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:42:31.629" endtime="20220908 14:42:31.629"/>
</kw>
<kw name="Preencher o campo &quot;${login_cpf_input_cpf}&quot; com o valor &quot;${CPF_registrado}&quot;" library="BaseApp" sourcename="Preencher o campo &quot;${elemento}&quot; com o valor &quot;${valor}&quot;">
<status status="NOT RUN" starttime="20220908 14:42:31.630" endtime="20220908 14:42:31.630"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_cpf_botao_avancar_cpf}</arg>
<status status="NOT RUN" starttime="20220908 14:42:31.631" endtime="20220908 14:42:31.631"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_informar_senha}&quot; deve ser &quot;Informe sua senha&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:42:31.639" endtime="20220908 14:42:31.639"/>
</kw>
<kw name="Preencher o campo &quot;${login_senha_input_senha}&quot; com o valor &quot;${senha_login_faker}&quot;" library="BaseApp" sourcename="Preencher o campo &quot;${elemento}&quot; com o valor &quot;${valor}&quot;">
<status status="NOT RUN" starttime="20220908 14:42:31.643" endtime="20220908 14:42:31.643"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_senha_botao_avancar}</arg>
<status status="NOT RUN" starttime="20220908 14:42:31.644" endtime="20220908 14:42:31.644"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_senha_erro_login}&quot; deve ser &quot;Não foi possível completar o login&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:42:31.647" endtime="20220908 14:42:31.647"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_mensagem_senha_incorreta}&quot; deve ser &quot;Parece que a senha está incorreta. Tente novamente!&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:42:31.648" endtime="20220908 14:42:31.648"/>
</kw>
<kw name="Preencher o campo &quot;${login_senha_input_senha}&quot; com o valor &quot;${senha_login_faker}&quot;" library="BaseApp" sourcename="Preencher o campo &quot;${elemento}&quot; com o valor &quot;${valor}&quot;">
<status status="NOT RUN" starttime="20220908 14:42:31.652" endtime="20220908 14:42:31.652"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_senha_botao_avancar}</arg>
<status status="NOT RUN" starttime="20220908 14:42:31.654" endtime="20220908 14:42:31.654"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_senha_erro_login}&quot; deve ser &quot;Não foi possível completar o login&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:42:31.655" endtime="20220908 14:42:31.655"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_mensagem_senha_incorreta}&quot; deve ser &quot;Parece que a senha está incorreta. Tente novamente!&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:42:31.656" endtime="20220908 14:42:31.657"/>
</kw>
<kw name="Preencher o campo &quot;${login_senha_input_senha}&quot; com o valor &quot;${senha_login_faker}&quot;" library="BaseApp" sourcename="Preencher o campo &quot;${elemento}&quot; com o valor &quot;${valor}&quot;">
<status status="NOT RUN" starttime="20220908 14:42:31.657" endtime="20220908 14:42:31.657"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_senha_botao_avancar}</arg>
<status status="NOT RUN" starttime="20220908 14:42:31.658" endtime="20220908 14:42:31.658"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_senha_bloqueada}&quot; deve ser &quot;Sua senha foi bloqueada :(&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:42:31.660" endtime="20220908 14:42:31.660"/>
</kw>
<kw name="O texto apresentado no campo &quot;${text_senha_bloqueada}&quot; deve ser &quot;Mas não se preocupe, você pode recupera-la em poucas etapas&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:42:31.663" endtime="20220908 14:42:31.663"/>
</kw>
<kw name="Fechar App" library="Setup">
<status status="NOT RUN" starttime="20220908 14:42:31.663" endtime="20220908 14:42:31.663"/>
</kw>
<status status="FAIL" starttime="20220908 14:42:11.070" endtime="20220908 14:42:31.666">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20301ms.
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20301ms.
    at getResponseForW3CError (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)</status>
</test>
<test id="s1-s1-t7" name="TC4828 - Validar senha bloqueada - Usuário salvo" line="92">
<kw name="Abrir App" library="Setup">
<kw name="Open Application" library="AppiumFlutterLibrary">
<arg>${APPIUM_SERVER}</arg>
<arg>automationName=${ATOMATION_NAME}</arg>
<arg>platformName=${PLATFORM_NAME}</arg>
<arg>deviceName=${DEVICE_NAME}</arg>
<arg>app=${APP_PATH}</arg>
<doc>Opens a new application to given Appium server.</doc>
<msg timestamp="20220908 14:42:38.212" level="FAIL">ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))</msg>
<status status="FAIL" starttime="20220908 14:42:31.674" endtime="20220908 14:42:38.222"/>
</kw>
<status status="FAIL" starttime="20220908 14:42:31.673" endtime="20220908 14:42:38.224"/>
</kw>
<kw name="O texto apresentado no campo &quot;${login_usuario_btn_entrar}&quot; deve ser &quot;Login&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:42:38.226" endtime="20220908 14:42:38.227"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_usuario_btn_entrar}</arg>
<status status="NOT RUN" starttime="20220908 14:42:38.227" endtime="20220908 14:42:38.228"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_informar_senha}&quot; deve ser &quot;Informe sua senha&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:42:38.229" endtime="20220908 14:42:38.229"/>
</kw>
<kw name="Preencher o campo &quot;${login_senha_input_senha}&quot; com o valor &quot;${senha_login_faker}&quot;" library="BaseApp" sourcename="Preencher o campo &quot;${elemento}&quot; com o valor &quot;${valor}&quot;">
<status status="NOT RUN" starttime="20220908 14:42:38.230" endtime="20220908 14:42:38.230"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_senha_botao_avancar}</arg>
<status status="NOT RUN" starttime="20220908 14:42:38.231" endtime="20220908 14:42:38.231"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_senha_erro_login}&quot; deve ser &quot;Parece que a senha está incorreta&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:42:38.234" endtime="20220908 14:42:38.234"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_mensagem_senha_incorreta}&quot; deve ser &quot;Parece que a senha está incorreta. Tente novamente!&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:42:38.236" endtime="20220908 14:42:38.237"/>
</kw>
<kw name="Preencher o campo &quot;${login_senha_input_senha}&quot; com o valor &quot;${senha_login_faker}&quot;" library="BaseApp" sourcename="Preencher o campo &quot;${elemento}&quot; com o valor &quot;${valor}&quot;">
<status status="NOT RUN" starttime="20220908 14:42:38.237" endtime="20220908 14:42:38.238"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_senha_botao_avancar}</arg>
<status status="NOT RUN" starttime="20220908 14:42:38.238" endtime="20220908 14:42:38.239"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_senha_erro_login}&quot; deve ser &quot;Parece que a senha está incorreta&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:42:38.239" endtime="20220908 14:42:38.240"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_mensagem_senha_incorreta}&quot; deve ser &quot;Parece que a senha está incorreta. Tente novamente!&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:42:38.246" endtime="20220908 14:42:38.246"/>
</kw>
<kw name="Preencher o campo &quot;${login_senha_input_senha}&quot; com o valor &quot;${senha_login_faker}&quot;" library="BaseApp" sourcename="Preencher o campo &quot;${elemento}&quot; com o valor &quot;${valor}&quot;">
<status status="NOT RUN" starttime="20220908 14:42:38.248" endtime="20220908 14:42:38.248"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_senha_botao_avancar}</arg>
<status status="NOT RUN" starttime="20220908 14:42:38.249" endtime="20220908 14:42:38.250"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_senha_bloqueada}&quot; deve ser &quot;Senha bloqueada :(&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:42:38.254" endtime="20220908 14:42:38.254"/>
</kw>
<kw name="O texto apresentado no campo &quot;${text_senha_bloqueada}&quot; deve ser &quot;Mas não se preocupe, você pode recupera-la em poucas etapas&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:42:38.257" endtime="20220908 14:42:38.257"/>
</kw>
<kw name="Fechar App" library="Setup">
<status status="NOT RUN" starttime="20220908 14:42:38.258" endtime="20220908 14:42:38.258"/>
</kw>
<status status="FAIL" starttime="20220908 14:42:31.671" endtime="20220908 14:42:38.260">ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))</status>
</test>
<test id="s1-s1-t8" name="TC4822 - Validar acesso a duvidas - Tela CPF" line="114">
<kw name="Abrir App" library="Setup">
<kw name="Open Application" library="AppiumFlutterLibrary">
<arg>${APPIUM_SERVER}</arg>
<arg>automationName=${ATOMATION_NAME}</arg>
<arg>platformName=${PLATFORM_NAME}</arg>
<arg>deviceName=${DEVICE_NAME}</arg>
<arg>app=${APP_PATH}</arg>
<doc>Opens a new application to given Appium server.</doc>
<msg timestamp="20220908 14:42:40.687" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F1019840&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20220908 14:42:43.130" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F1019930&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20220908 14:42:45.564" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F1019A80&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20220908 14:42:47.841" level="FAIL">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F1019BD0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</msg>
<status status="FAIL" starttime="20220908 14:42:38.270" endtime="20220908 14:42:47.843"/>
</kw>
<status status="FAIL" starttime="20220908 14:42:38.267" endtime="20220908 14:42:47.845"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${inicial_botao_ja_sou_cliente}</arg>
<status status="NOT RUN" starttime="20220908 14:42:47.846" endtime="20220908 14:42:47.846"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_cpf_texto_cpf}&quot; deve ser &quot;Informe seu CPF para entrar&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:42:47.847" endtime="20220908 14:42:47.847"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_cpf_botao_ajuda}</arg>
<status status="NOT RUN" starttime="20220908 14:42:47.848" endtime="20220908 14:42:47.848"/>
</kw>
<kw name="Fechar App" library="Setup">
<status status="NOT RUN" starttime="20220908 14:42:47.849" endtime="20220908 14:42:47.849"/>
</kw>
<status status="FAIL" starttime="20220908 14:42:38.264" endtime="20220908 14:42:47.851">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F1019BD0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</status>
</test>
<test id="s1-s1-t9" name="TC4893 - Validar acesso a duvidas - Tela senha - 1º Acesso" line="122">
<kw name="Abrir App" library="Setup">
<kw name="Open Application" library="AppiumFlutterLibrary">
<arg>${APPIUM_SERVER}</arg>
<arg>automationName=${ATOMATION_NAME}</arg>
<arg>platformName=${PLATFORM_NAME}</arg>
<arg>deviceName=${DEVICE_NAME}</arg>
<arg>app=${APP_PATH}</arg>
<doc>Opens a new application to given Appium server.</doc>
<msg timestamp="20220908 14:43:52.760" level="FAIL">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
    at getResponseForW3CError (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)</msg>
<status status="FAIL" starttime="20220908 14:42:47.861" endtime="20220908 14:43:52.762"/>
</kw>
<status status="FAIL" starttime="20220908 14:42:47.860" endtime="20220908 14:43:52.764"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${inicial_botao_ja_sou_cliente}</arg>
<status status="NOT RUN" starttime="20220908 14:43:52.768" endtime="20220908 14:43:52.768"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_cpf_texto_cpf}&quot; deve ser &quot;Informe seu CPF para entrar&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:43:52.768" endtime="20220908 14:43:52.769"/>
</kw>
<kw name="Preencher o campo &quot;${login_cpf_input_cpf}&quot; com o valor &quot;${CPF_registrado}&quot;" library="BaseApp" sourcename="Preencher o campo &quot;${elemento}&quot; com o valor &quot;${valor}&quot;">
<status status="NOT RUN" starttime="20220908 14:43:52.770" endtime="20220908 14:43:52.770"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_cpf_botao_avancar_cpf}</arg>
<status status="NOT RUN" starttime="20220908 14:43:52.771" endtime="20220908 14:43:52.771"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_informar_senha}&quot; deve ser &quot;Informe sua senha&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:43:52.772" endtime="20220908 14:43:52.772"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_senha_botao_ajuda}</arg>
<status status="NOT RUN" starttime="20220908 14:43:52.772" endtime="20220908 14:43:52.772"/>
</kw>
<kw name="Fechar App" library="Setup">
<status status="NOT RUN" starttime="20220908 14:43:52.774" endtime="20220908 14:43:52.774"/>
</kw>
<status status="FAIL" starttime="20220908 14:42:47.854" endtime="20220908 14:43:52.776">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
    at getResponseForW3CError (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)</status>
</test>
<test id="s1-s1-t10" name="TC4893 - Validar acesso a duvidas - Tela informar token" line="132">
<kw name="Abrir App" library="Setup">
<kw name="Open Application" library="AppiumFlutterLibrary">
<arg>${APPIUM_SERVER}</arg>
<arg>automationName=${ATOMATION_NAME}</arg>
<arg>platformName=${PLATFORM_NAME}</arg>
<arg>deviceName=${DEVICE_NAME}</arg>
<arg>app=${APP_PATH}</arg>
<doc>Opens a new application to given Appium server.</doc>
<msg timestamp="20220908 14:44:26.123" level="FAIL">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
    at getResponseForW3CError (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)</msg>
<status status="FAIL" starttime="20220908 14:43:52.784" endtime="20220908 14:44:26.125"/>
</kw>
<status status="FAIL" starttime="20220908 14:43:52.783" endtime="20220908 14:44:26.128"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${inicial_botao_ja_sou_cliente}</arg>
<status status="NOT RUN" starttime="20220908 14:44:26.130" endtime="20220908 14:44:26.130"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_cpf_texto_cpf}&quot; deve ser &quot;Informe seu CPF para entrar&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:44:26.131" endtime="20220908 14:44:26.131"/>
</kw>
<kw name="Preencher o campo &quot;${login_cpf_input_cpf}&quot; com o valor &quot;${cpf_registrado_com_token}&quot;" library="BaseApp" sourcename="Preencher o campo &quot;${elemento}&quot; com o valor &quot;${valor}&quot;">
<status status="NOT RUN" starttime="20220908 14:44:26.132" endtime="20220908 14:44:26.132"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_cpf_botao_avancar_cpf}</arg>
<status status="NOT RUN" starttime="20220908 14:44:26.133" endtime="20220908 14:44:26.133"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_informar_senha}&quot; deve ser &quot;Informe sua senha&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:44:26.134" endtime="20220908 14:44:26.134"/>
</kw>
<kw name="Preencher o campo &quot;${login_senha_input_senha}&quot; com o valor &quot;${senha_login_padrao}&quot;" library="BaseApp" sourcename="Preencher o campo &quot;${elemento}&quot; com o valor &quot;${valor}&quot;">
<status status="NOT RUN" starttime="20220908 14:44:26.135" endtime="20220908 14:44:26.135"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_senha_botao_avancar}</arg>
<status status="NOT RUN" starttime="20220908 14:44:26.136" endtime="20220908 14:44:26.137"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_informar_token}&quot; deve ser &quot;Informe abaixo o código que enviamos para o seu celular com final&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:44:26.137" endtime="20220908 14:44:26.138"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_senha_botao_ajuda}</arg>
<status status="NOT RUN" starttime="20220908 14:44:26.138" endtime="20220908 14:44:26.139"/>
</kw>
<kw name="Fechar App" library="Setup">
<status status="NOT RUN" starttime="20220908 14:44:26.140" endtime="20220908 14:44:26.140"/>
</kw>
<status status="FAIL" starttime="20220908 14:43:52.781" endtime="20220908 14:44:26.141">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
    at getResponseForW3CError (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)</status>
</test>
<test id="s1-s1-t11" name="TC4823 - Validar login de usuário salvo" line="146">
<kw name="Abrir App" library="Setup">
<kw name="Open Application" library="AppiumFlutterLibrary">
<arg>${APPIUM_SERVER}</arg>
<arg>automationName=${ATOMATION_NAME}</arg>
<arg>platformName=${PLATFORM_NAME}</arg>
<arg>deviceName=${DEVICE_NAME}</arg>
<arg>app=${APP_PATH}</arg>
<doc>Opens a new application to given Appium server.</doc>
<msg timestamp="20220908 14:44:55.841" level="FAIL">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
    at getResponseForW3CError (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)</msg>
<status status="FAIL" starttime="20220908 14:44:26.147" endtime="20220908 14:44:55.843"/>
</kw>
<status status="FAIL" starttime="20220908 14:44:26.146" endtime="20220908 14:44:55.845"/>
</kw>
<kw name="O texto apresentado no campo &quot;${login_usuario_btn_entrar}&quot; deve ser &quot;Login&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:44:55.847" endtime="20220908 14:44:55.847"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_usuario_btn_entrar}</arg>
<status status="NOT RUN" starttime="20220908 14:44:55.848" endtime="20220908 14:44:55.849"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_informar_senha}&quot; deve ser &quot;Informe sua senha&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:44:55.849" endtime="20220908 14:44:55.850"/>
</kw>
<kw name="Preencher o campo &quot;${login_senha_input_senha}&quot; com o valor &quot;${senha_login_padrao}&quot;" library="BaseApp" sourcename="Preencher o campo &quot;${elemento}&quot; com o valor &quot;${valor}&quot;">
<status status="NOT RUN" starttime="20220908 14:44:55.850" endtime="20220908 14:44:55.851"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_senha_botao_avancar}</arg>
<status status="NOT RUN" starttime="20220908 14:44:55.851" endtime="20220908 14:44:55.851"/>
</kw>
<kw name="Aguardar carregamento" library="BaseApp">
<arg>${home_botao_desty}</arg>
<status status="NOT RUN" starttime="20220908 14:44:55.852" endtime="20220908 14:44:55.852"/>
</kw>
<kw name="Fechar App" library="Setup">
<status status="NOT RUN" starttime="20220908 14:44:55.853" endtime="20220908 14:44:55.853"/>
</kw>
<status status="FAIL" starttime="20220908 14:44:26.144" endtime="20220908 14:44:55.855">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
    at getResponseForW3CError (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)</status>
</test>
<test id="s1-s1-t12" name="TC4824 - Validar token de usuário incorreto" line="156">
<kw name="Abrir App" library="Setup">
<kw name="Open Application" library="AppiumFlutterLibrary">
<arg>${APPIUM_SERVER}</arg>
<arg>automationName=${ATOMATION_NAME}</arg>
<arg>platformName=${PLATFORM_NAME}</arg>
<arg>deviceName=${DEVICE_NAME}</arg>
<arg>app=${APP_PATH}</arg>
<doc>Opens a new application to given Appium server.</doc>
<msg timestamp="20220908 14:45:24.504" level="FAIL">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
    at getResponseForW3CError (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)</msg>
<status status="FAIL" starttime="20220908 14:44:55.862" endtime="20220908 14:45:24.506"/>
</kw>
<status status="FAIL" starttime="20220908 14:44:55.861" endtime="20220908 14:45:24.508"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${inicial_botao_ja_sou_cliente}</arg>
<status status="NOT RUN" starttime="20220908 14:45:24.511" endtime="20220908 14:45:24.511"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_cpf_texto_cpf}&quot; deve ser &quot;Informe seu CPF para entrar&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:45:24.512" endtime="20220908 14:45:24.513"/>
</kw>
<kw name="Preencher o campo &quot;${login_cpf_input_cpf}&quot; com o valor &quot;${cpf_registrado_com_token}&quot;" library="BaseApp" sourcename="Preencher o campo &quot;${elemento}&quot; com o valor &quot;${valor}&quot;">
<status status="NOT RUN" starttime="20220908 14:45:24.515" endtime="20220908 14:45:24.515"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_cpf_botao_avancar_cpf}</arg>
<status status="NOT RUN" starttime="20220908 14:45:24.516" endtime="20220908 14:45:24.517"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_informar_senha}&quot; deve ser &quot;Informe sua senha&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:45:24.518" endtime="20220908 14:45:24.518"/>
</kw>
<kw name="Preencher o campo &quot;${login_senha_input_senha}&quot; com o valor &quot;${senha_login_padrao}&quot;" library="BaseApp" sourcename="Preencher o campo &quot;${elemento}&quot; com o valor &quot;${valor}&quot;">
<status status="NOT RUN" starttime="20220908 14:45:24.519" endtime="20220908 14:45:24.519"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_senha_botao_avancar}</arg>
<status status="NOT RUN" starttime="20220908 14:45:24.520" endtime="20220908 14:45:24.520"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_informar_token}&quot; deve ser &quot;Informe abaixo o código que enviamos para o seu celular com final&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:45:24.520" endtime="20220908 14:45:24.521"/>
</kw>
<kw name="Preencher o campo &quot;${label_token_input}&quot; com o valor &quot;${senha_login_faker}&quot;" library="BaseApp" sourcename="Preencher o campo &quot;${elemento}&quot; com o valor &quot;${valor}&quot;">
<status status="NOT RUN" starttime="20220908 14:45:24.532" endtime="20220908 14:45:24.532"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_token_mensagem_erro_token}&quot; deve ser &quot;Ops! O código inserido está incorreto&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:45:24.534" endtime="20220908 14:45:24.534"/>
</kw>
<kw name="Fechar App" library="Setup">
<status status="NOT RUN" starttime="20220908 14:45:24.535" endtime="20220908 14:45:24.535"/>
</kw>
<status status="FAIL" starttime="20220908 14:44:55.859" endtime="20220908 14:45:24.540">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
    at getResponseForW3CError (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)</status>
</test>
<test id="s1-s1-t13" name="TC4825 - Validar primeiro login" line="170">
<kw name="Abrir App" library="Setup">
<kw name="Open Application" library="AppiumFlutterLibrary">
<arg>${APPIUM_SERVER}</arg>
<arg>automationName=${ATOMATION_NAME}</arg>
<arg>platformName=${PLATFORM_NAME}</arg>
<arg>deviceName=${DEVICE_NAME}</arg>
<arg>app=${APP_PATH}</arg>
<doc>Opens a new application to given Appium server.</doc>
<msg timestamp="20220908 14:45:52.374" level="FAIL">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
    at getResponseForW3CError (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)</msg>
<status status="FAIL" starttime="20220908 14:45:24.551" endtime="20220908 14:45:52.375"/>
</kw>
<status status="FAIL" starttime="20220908 14:45:24.550" endtime="20220908 14:45:52.378"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${inicial_botao_ja_sou_cliente}</arg>
<status status="NOT RUN" starttime="20220908 14:45:52.380" endtime="20220908 14:45:52.381"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_cpf_texto_cpf}&quot; deve ser &quot;Informe seu CPF para entrar&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:45:52.383" endtime="20220908 14:45:52.383"/>
</kw>
<kw name="Preencher o campo &quot;${login_cpf_input_cpf}&quot; com o valor &quot;${CPF_registrado}&quot;" library="BaseApp" sourcename="Preencher o campo &quot;${elemento}&quot; com o valor &quot;${valor}&quot;">
<status status="NOT RUN" starttime="20220908 14:45:52.383" endtime="20220908 14:45:52.384"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_cpf_botao_avancar_cpf}</arg>
<status status="NOT RUN" starttime="20220908 14:45:52.385" endtime="20220908 14:45:52.385"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_informar_senha}&quot; deve ser &quot;Informe sua senha&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:45:52.385" endtime="20220908 14:45:52.386"/>
</kw>
<kw name="Preencher o campo &quot;${login_senha_input_senha}&quot; com o valor &quot;${senha_login_padrao}&quot;" library="BaseApp" sourcename="Preencher o campo &quot;${elemento}&quot; com o valor &quot;${valor}&quot;">
<status status="NOT RUN" starttime="20220908 14:45:52.386" endtime="20220908 14:45:52.386"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_senha_botao_avancar}</arg>
<status status="NOT RUN" starttime="20220908 14:45:52.388" endtime="20220908 14:45:52.388"/>
</kw>
<kw name="Aguardar carregamento" library="BaseApp">
<arg>${login_autorizacao_botao_nao}</arg>
<status status="NOT RUN" starttime="20220908 14:45:52.389" endtime="20220908 14:45:52.389"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_autorizacao_botao_nao}</arg>
<status status="NOT RUN" starttime="20220908 14:45:52.392" endtime="20220908 14:45:52.392"/>
</kw>
<kw name="Aguardar carregamento" library="BaseApp">
<arg>${home_botao_desty}</arg>
<status status="NOT RUN" starttime="20220908 14:45:52.393" endtime="20220908 14:45:52.393"/>
</kw>
<kw name="Fechar App" library="Setup">
<status status="NOT RUN" starttime="20220908 14:45:52.394" endtime="20220908 14:45:52.394"/>
</kw>
<status status="FAIL" starttime="20220908 14:45:24.549" endtime="20220908 14:45:52.396">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
    at getResponseForW3CError (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)</status>
</test>
<test id="s1-s1-t14" name="TC4826 - Validar conta inativa" line="184">
<kw name="Abrir App" library="Setup">
<kw name="Open Application" library="AppiumFlutterLibrary">
<arg>${APPIUM_SERVER}</arg>
<arg>automationName=${ATOMATION_NAME}</arg>
<arg>platformName=${PLATFORM_NAME}</arg>
<arg>deviceName=${DEVICE_NAME}</arg>
<arg>app=${APP_PATH}</arg>
<doc>Opens a new application to given Appium server.</doc>
<msg timestamp="20220908 14:46:22.117" level="FAIL">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
    at getResponseForW3CError (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)</msg>
<status status="FAIL" starttime="20220908 14:45:52.406" endtime="20220908 14:46:22.119"/>
</kw>
<status status="FAIL" starttime="20220908 14:45:52.404" endtime="20220908 14:46:22.121"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${inicial_botao_ja_sou_cliente}</arg>
<status status="NOT RUN" starttime="20220908 14:46:22.126" endtime="20220908 14:46:22.127"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_cpf_texto_cpf}&quot; deve ser &quot;Informe seu CPF para entrar&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:46:22.129" endtime="20220908 14:46:22.129"/>
</kw>
<kw name="Preencher o campo &quot;${login_cpf_input_cpf}&quot; com o valor &quot;${cpf_conta_inativa}&quot;" library="BaseApp" sourcename="Preencher o campo &quot;${elemento}&quot; com o valor &quot;${valor}&quot;">
<status status="NOT RUN" starttime="20220908 14:46:22.130" endtime="20220908 14:46:22.131"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_cpf_botao_avancar_cpf}</arg>
<status status="NOT RUN" starttime="20220908 14:46:22.132" endtime="20220908 14:46:22.132"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_informar_senha}&quot; deve ser &quot;Informe sua senha&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:46:22.132" endtime="20220908 14:46:22.133"/>
</kw>
<kw name="Preencher o campo &quot;${login_senha_input_senha}&quot; com o valor &quot;${senha_login_padrao}&quot;" library="BaseApp" sourcename="Preencher o campo &quot;${elemento}&quot; com o valor &quot;${valor}&quot;">
<status status="NOT RUN" starttime="20220908 14:46:22.134" endtime="20220908 14:46:22.135"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_senha_botao_avancar}</arg>
<status status="NOT RUN" starttime="20220908 14:46:22.136" endtime="20220908 14:46:22.137"/>
</kw>
<kw name="Aguardar carregamento" library="BaseApp">
<arg>${login_inativo_botao_desty}</arg>
<status status="NOT RUN" starttime="20220908 14:46:22.137" endtime="20220908 14:46:22.137"/>
</kw>
<kw name="O texto apresentado no campo &quot;${login_inativo_texto_titulo}&quot; deve ser &quot;Esta conta está temporariamente inativa&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:46:22.139" endtime="20220908 14:46:22.139"/>
</kw>
<kw name="O texto apresentado no campo &quot;${login_inativo_texto_corpo}&quot; deve ser &quot;${texto_corpo}&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:46:22.140" endtime="20220908 14:46:22.140"/>
</kw>
<kw name="Aguardar carregamento" library="BaseApp">
<arg>${chat_botao}</arg>
<status status="NOT RUN" starttime="20220908 14:46:22.141" endtime="20220908 14:46:22.141"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_inativo_botao_fechar}</arg>
<status status="NOT RUN" starttime="20220908 14:46:22.142" endtime="20220908 14:46:22.143"/>
</kw>
<kw name="Fechar App" library="Setup">
<status status="NOT RUN" starttime="20220908 14:46:22.143" endtime="20220908 14:46:22.144"/>
</kw>
<status status="FAIL" starttime="20220908 14:45:52.403" endtime="20220908 14:46:22.150">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
    at getResponseForW3CError (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)</status>
</test>
<test id="s1-s1-t15" name="TC4829 - Validar reenvio do token" line="200">
<kw name="Abrir App" library="Setup">
<kw name="Open Application" library="AppiumFlutterLibrary">
<arg>${APPIUM_SERVER}</arg>
<arg>automationName=${ATOMATION_NAME}</arg>
<arg>platformName=${PLATFORM_NAME}</arg>
<arg>deviceName=${DEVICE_NAME}</arg>
<arg>app=${APP_PATH}</arg>
<doc>Opens a new application to given Appium server.</doc>
<msg timestamp="20220908 14:46:52.087" level="FAIL">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
    at getResponseForW3CError (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)</msg>
<status status="FAIL" starttime="20220908 14:46:22.165" endtime="20220908 14:46:52.089"/>
</kw>
<status status="FAIL" starttime="20220908 14:46:22.163" endtime="20220908 14:46:52.091"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${inicial_botao_ja_sou_cliente}</arg>
<status status="NOT RUN" starttime="20220908 14:46:52.098" endtime="20220908 14:46:52.098"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_cpf_texto_cpf}&quot; deve ser &quot;Informe seu CPF para entrar&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:46:52.101" endtime="20220908 14:46:52.102"/>
</kw>
<kw name="Preencher o campo &quot;${login_cpf_input_cpf}&quot; com o valor &quot;${cpf_registrado_com_token}&quot;" library="BaseApp" sourcename="Preencher o campo &quot;${elemento}&quot; com o valor &quot;${valor}&quot;">
<status status="NOT RUN" starttime="20220908 14:46:52.106" endtime="20220908 14:46:52.106"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_cpf_botao_avancar_cpf}</arg>
<status status="NOT RUN" starttime="20220908 14:46:52.108" endtime="20220908 14:46:52.108"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_informar_senha}&quot; deve ser &quot;Informe sua senha&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:46:52.109" endtime="20220908 14:46:52.109"/>
</kw>
<kw name="Preencher o campo &quot;${login_senha_input_senha}&quot; com o valor &quot;${senha_login_padrao}&quot;" library="BaseApp" sourcename="Preencher o campo &quot;${elemento}&quot; com o valor &quot;${valor}&quot;">
<status status="NOT RUN" starttime="20220908 14:46:52.110" endtime="20220908 14:46:52.110"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_senha_botao_avancar}</arg>
<status status="NOT RUN" starttime="20220908 14:46:52.111" endtime="20220908 14:46:52.111"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_informar_token}&quot; deve ser &quot;Informe abaixo o código que enviamos para o seu celular com final&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:46:52.112" endtime="20220908 14:46:52.113"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_token_botao_reenviar}</arg>
<status status="NOT RUN" starttime="20220908 14:46:52.114" endtime="20220908 14:46:52.114"/>
</kw>
<kw name="Aguardar carregamento" library="BaseApp">
<arg>${reenviar_token_texto_temporizador}</arg>
<status status="NOT RUN" starttime="20220908 14:46:52.114" endtime="20220908 14:46:52.114"/>
</kw>
<kw name="Aguardar carregamento" library="BaseApp">
<arg>${reenviar_token_botao_cancelar}</arg>
<status status="NOT RUN" starttime="20220908 14:46:52.115" endtime="20220908 14:46:52.116"/>
</kw>
<kw name="Aguardar carregamento" library="BaseApp">
<arg>${reenviar_token_botao_reenviar_desabilitado}</arg>
<status status="NOT RUN" starttime="20220908 14:46:52.117" endtime="20220908 14:46:52.117"/>
</kw>
<kw name="O texto apresentado no campo &quot;${reenviar_token_texto_titulo}&quot; deve ser &quot;Ainda não recebeu o SMS com o código de ace">
<status status="NOT RUN" starttime="20220908 14:46:52.129" endtime="20220908 14:46:52.130"/>
</kw>
<kw name="O texto apresentado no campo &quot;${reenviar_token_texto_temporizador}&quot; deve ser &quot;00:00s&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:46:52.131" endtime="20220908 14:46:52.131"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${reenviar_token_botao_reenviar_habilitado}</arg>
<status status="NOT RUN" starttime="20220908 14:46:52.136" endtime="20220908 14:46:52.136"/>
</kw>
<kw name="O texto apresentado no campo &quot;${reenviar_token_texto_temporizador}&quot; deve ser &quot;00:59s&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:46:52.137" endtime="20220908 14:46:52.137"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${reenviar_token_botao_cancelar}</arg>
<status status="NOT RUN" starttime="20220908 14:46:52.140" endtime="20220908 14:46:52.140"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_informar_token}&quot; deve ser &quot;Informe abaixo o código que enviamos para o seu celular com final&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:46:52.145" endtime="20220908 14:46:52.145"/>
</kw>
<kw name="Fechar App" library="Setup">
<status status="NOT RUN" starttime="20220908 14:46:52.146" endtime="20220908 14:46:52.147"/>
</kw>
<status status="FAIL" starttime="20220908 14:46:22.159" endtime="20220908 14:46:52.149">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
    at getResponseForW3CError (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)</status>
</test>
<test id="s1-s1-t16" name="TC4830 - Validar acesso Pix" line="223">
<kw name="Abrir App" library="Setup">
<kw name="Open Application" library="AppiumFlutterLibrary">
<arg>${APPIUM_SERVER}</arg>
<arg>automationName=${ATOMATION_NAME}</arg>
<arg>platformName=${PLATFORM_NAME}</arg>
<arg>deviceName=${DEVICE_NAME}</arg>
<arg>app=${APP_PATH}</arg>
<doc>Opens a new application to given Appium server.</doc>
<msg timestamp="20220908 14:47:20.852" level="FAIL">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
    at getResponseForW3CError (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)</msg>
<status status="FAIL" starttime="20220908 14:46:52.170" endtime="20220908 14:47:20.855"/>
</kw>
<status status="FAIL" starttime="20220908 14:46:52.168" endtime="20220908 14:47:20.859"/>
</kw>
<kw name="O texto apresentado no campo &quot;${login_usuario_btn_entrar}&quot; deve ser &quot;Login&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:47:20.862" endtime="20220908 14:47:20.862"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_usuario_btn_pix}</arg>
<status status="NOT RUN" starttime="20220908 14:47:20.866" endtime="20220908 14:47:20.866"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_informar_senha}&quot; deve ser &quot;Informe sua senha&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:47:20.867" endtime="20220908 14:47:20.867"/>
</kw>
<kw name="Preencher o campo &quot;${login_senha_input_senha}&quot; com o valor &quot;${senha_login_padrao}&quot;" library="BaseApp" sourcename="Preencher o campo &quot;${elemento}&quot; com o valor &quot;${valor}&quot;">
<status status="NOT RUN" starttime="20220908 14:47:20.871" endtime="20220908 14:47:20.871"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_senha_botao_avancar}</arg>
<status status="NOT RUN" starttime="20220908 14:47:20.873" endtime="20220908 14:47:20.873"/>
</kw>
<kw name="O texto apresentado no campo &quot;${area_pix_texto_titulo}&quot; deve ser &quot;Pix&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:47:20.877" endtime="20220908 14:47:20.877"/>
</kw>
<kw name="Fechar App" library="Setup">
<status status="NOT RUN" starttime="20220908 14:47:20.878" endtime="20220908 14:47:20.878"/>
</kw>
<status status="FAIL" starttime="20220908 14:46:52.165" endtime="20220908 14:47:20.880">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
    at getResponseForW3CError (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)</status>
</test>
<test id="s1-s1-t17" name="TC4831 - Validar acesso compartilhamento da conta" line="233">
<kw name="Abrir App" library="Setup">
<kw name="Open Application" library="AppiumFlutterLibrary">
<arg>${APPIUM_SERVER}</arg>
<arg>automationName=${ATOMATION_NAME}</arg>
<arg>platformName=${PLATFORM_NAME}</arg>
<arg>deviceName=${DEVICE_NAME}</arg>
<arg>app=${APP_PATH}</arg>
<doc>Opens a new application to given Appium server.</doc>
<msg timestamp="20220908 14:47:50.076" level="FAIL">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
    at getResponseForW3CError (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)</msg>
<status status="FAIL" starttime="20220908 14:47:20.893" endtime="20220908 14:47:50.078"/>
</kw>
<status status="FAIL" starttime="20220908 14:47:20.891" endtime="20220908 14:47:50.079"/>
</kw>
<kw name="O texto apresentado no campo &quot;${login_usuario_btn_entrar}&quot; deve ser &quot;Login&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:47:50.081" endtime="20220908 14:47:50.081"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_usuario_btn_compartilhar_conta}</arg>
<status status="NOT RUN" starttime="20220908 14:47:50.082" endtime="20220908 14:47:50.082"/>
</kw>
<kw name="Fechar App" library="Setup">
<status status="NOT RUN" starttime="20220908 14:47:50.082" endtime="20220908 14:47:50.082"/>
</kw>
<status status="FAIL" starttime="20220908 14:47:20.887" endtime="20220908 14:47:50.083">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
    at getResponseForW3CError (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)</status>
</test>
<test id="s1-s1-t18" name="TC4832 - Validar opção de troca de conta" line="240">
<kw name="Abrir App" library="Setup">
<kw name="Open Application" library="AppiumFlutterLibrary">
<arg>${APPIUM_SERVER}</arg>
<arg>automationName=${ATOMATION_NAME}</arg>
<arg>platformName=${PLATFORM_NAME}</arg>
<arg>deviceName=${DEVICE_NAME}</arg>
<arg>app=${APP_PATH}</arg>
<doc>Opens a new application to given Appium server.</doc>
<msg timestamp="20220908 14:48:18.829" level="FAIL">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
    at getResponseForW3CError (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)</msg>
<status status="FAIL" starttime="20220908 14:47:50.091" endtime="20220908 14:48:18.831"/>
</kw>
<status status="FAIL" starttime="20220908 14:47:50.089" endtime="20220908 14:48:18.833"/>
</kw>
<kw name="O texto apresentado no campo &quot;${login_usuario_btn_entrar}&quot; deve ser &quot;Login&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:48:18.834" endtime="20220908 14:48:18.835"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_usuario_btn_trocar_conta}</arg>
<status status="NOT RUN" starttime="20220908 14:48:18.835" endtime="20220908 14:48:18.835"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_cpf_texto_cpf}&quot; deve ser &quot;Informe seu CPF para entrar&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:48:18.836" endtime="20220908 14:48:18.837"/>
</kw>
<kw name="Fechar App" library="Setup">
<status status="NOT RUN" starttime="20220908 14:48:18.838" endtime="20220908 14:48:18.838"/>
</kw>
<status status="FAIL" starttime="20220908 14:47:50.087" endtime="20220908 14:48:18.840">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
    at getResponseForW3CError (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)</status>
</test>
<test id="s1-s1-t19" name="TC4833 - Validar x na área de usuário logado" line="247">
<kw name="Abrir App" library="Setup">
<kw name="Open Application" library="AppiumFlutterLibrary">
<arg>${APPIUM_SERVER}</arg>
<arg>automationName=${ATOMATION_NAME}</arg>
<arg>platformName=${PLATFORM_NAME}</arg>
<arg>deviceName=${DEVICE_NAME}</arg>
<arg>app=${APP_PATH}</arg>
<doc>Opens a new application to given Appium server.</doc>
<msg timestamp="20220908 14:48:49.407" level="FAIL">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
    at getResponseForW3CError (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)</msg>
<status status="FAIL" starttime="20220908 14:48:18.850" endtime="20220908 14:48:49.410"/>
</kw>
<status status="FAIL" starttime="20220908 14:48:18.848" endtime="20220908 14:48:49.412"/>
</kw>
<kw name="O texto apresentado no campo &quot;${login_usuario_btn_entrar}&quot; deve ser &quot;Login&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:48:49.418" endtime="20220908 14:48:49.418"/>
</kw>
<kw name="Clicar em" library="BaseApp">
<arg>${login_usuario_btn_fechar}</arg>
<status status="NOT RUN" starttime="20220908 14:48:49.420" endtime="20220908 14:48:49.420"/>
</kw>
<kw name="O texto apresentado no campo &quot;${label_cpf_texto_cpf}&quot; deve ser &quot;Informe seu CPF para entrar&quot;" library="BaseApp" sourcename="O texto apresentado no campo &quot;${elemento}&quot; deve ser &quot;${texto_esperado}&quot;">
<status status="NOT RUN" starttime="20220908 14:48:49.421" endtime="20220908 14:48:49.421"/>
</kw>
<kw name="Fechar App" library="Setup">
<status status="NOT RUN" starttime="20220908 14:48:49.422" endtime="20220908 14:48:49.422"/>
</kw>
<status status="FAIL" starttime="20220908 14:48:18.846" endtime="20220908 14:48:49.423">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined
    at getResponseForW3CError (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\ju_le\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)</status>
</test>
<status status="FAIL" starttime="20220908 14:41:01.666" endtime="20220908 14:48:49.435"/>
</suite>
<status status="FAIL" starttime="20220908 14:41:01.629" endtime="20220908 14:48:49.453"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="19" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="19" skip="0" id="s1" name="Login-Test">Login-Test</stat>
<stat pass="0" fail="19" skip="0" id="s1-s1" name="LoginTest">Login-Test.LoginTest</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20220908 14:41:06.285" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0ED8B50&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20220908 14:41:08.703" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0EC3460&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20220908 14:41:11.047" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0EC0400&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20220908 14:41:15.214" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0EDAB00&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20220908 14:41:17.251" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0ED9420&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20220908 14:41:19.302" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0EDABF0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20220908 14:41:23.442" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0FD86D0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20220908 14:41:25.489" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0FD87C0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20220908 14:41:27.538" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0FD8910&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20220908 14:41:31.652" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0FDA170&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20220908 14:41:33.701" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0FDA260&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20220908 14:41:35.738" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0FDA3B0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20220908 14:41:39.855" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0FD9A50&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20220908 14:41:41.908" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F0FD9C90&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20220908 14:42:40.687" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F1019840&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20220908 14:42:43.130" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F1019930&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20220908 14:42:45.564" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000001B6F1019A80&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
</errors>
</robot>
